name:                fxhitori
version:             0.1.0.0
github:              "nrpeterson/fxhitori"
license:             GPL-3.0-or-later
author:              "Nick Peterson"
maintainer:          "nick@nrp.dev"
copyright:           "2020 Nick Peterson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nrpeterson/fxhitori#readme>

default-extensions:
- TupleSections
- RankNTypes
- FlexibleContexts

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers
- microlens-platform

library:
  source-dirs: src

executables:
  fxhitori-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fxhitori

tests:
  fxhitori-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fxhitori
